[build]
  base = "."
  functions = "./functions"
  publish = "public"
  command = "gatsby build"
[build.environment]
  NODE_VERSION = "12.13.0"
  YARN_VERSION = "1.19.1"
  YARN_FLAGS = "--no-ignore-optional"
[[plugins]]
package = "netlify-plugin-checklinks"

  [plugins.inputs]
  todoPatterns = ["www.google-analytics.com, https://fonts.googleapis.com/css2?family=Spectral:ital,wght@0,400;600;0,700;1,400;1,800&display=swap"]
  checkExternal = false